### ISSUE TITLE
Images are coming out pixeled

### ISSUE THREAD

**Issue by YogiYang** [TurboPack/PowerPDF#1]
I am using PowerPDF to generate PDF documents that contain text as well as many thumbnails of images. The size of Image control for PowerPDF is set to 100 width and height.

I am loading images programmatically using ImageEn VCL.

Here is the download link to a sample PDF generated using PowerPDF.
https://www.dropbox.com/s/9uv23kqql7qr3c7/projectdetails.pdf?dl=0

Code snippet that I am using to load Image in PowerPDF Image Control
`ieTemp.Proc.Resample(150, -1, TResampleFilter(0));`
`pdfImageR1C2.Picture.Assign(ieTemp.Bitmap);`

TIA

Yogi Yang

**Comment by romankassebaum** [comment]
I have no idea.

First question: How looks the image after "ieTemp.Proc.Resample(150, -1, TResampleFilter(0));"? Can you save it to file and check it?

Second question: How looks the image after "pdfImageR1C2.Picture.Assign(ieTemp.Bitmap);"? Please also check it.

**Comment by YogiYang** [comment]
I checked. The thumbnails come properly. I also tried with other resmaple filters but the result is the same.
After assigning the image to the picture property the images looks good on screen but gets pixeled in the PDF that gets saved.

TIA

Yogi Yang
