### ISSUE TITLE
Class Arial not found error

### ISSUE THREAD

**Issue by JGMSPY** [TurboPack/PowerPDF#14]
Either installed via GitHub or through GetIt, in both cases dropping a PrPage component on a VCL form fails.
Window 11 has the Arial class installed by default, thus is not suspected for causing the error. Neither is Delphi 12, which runs normally.
I compared the file PDFFonts.pas in Delphi12 and Delphi11 and found only one difference: "sysutils"was missing in the D12 version. 
Can that be the reason why?

**Comment by romankassebaum** [comment]
I copied some Register code to the design time package. Then I could drop a TPrPage on a form.

**Comment by JGMSPY** [comment]
JonRobertson on DelphiPraxis.net [en] posted a working solution too, but having it fixed upfront is ofcourse the best.
Thank you.

**Comment by Ibrachess** [comment]
I'm trying to install the package (Embarcadero® Delphi 11 Version 28.0.48361.3236) and I'm getting the following error:
"Registration procedure, Powerpdf.Register in package c:\..... raised exception class EListError : Duplicates not allowed".
If I comment the following lines
RegisterClassAlias(TPdfFixedWidth, 'FixedWidth');
  RegisterClassAlias(TPdfFixedWidthBold, 'FixedWidth-Bold');
  RegisterClassAlias(TPdfFixedWidthBoldItalic, 'FixedWidth-BoldItalic');
  RegisterClassAlias(TPdfFixedWidthItalic, 'FixedWidth-Italic');
  RegisterClassAlias(TPdfArial, 'Arial');
  RegisterClassAlias(TPdfArialBold, 'Arial-Bold');

  RegisterClassAlias(TPdfArialBoldItalic, 'Arial-BoldItalic');
  RegisterClassAlias(TPdfArialItalic, 'Arial-Italic');
  RegisterClassAlias(TPdfTimesRoman, 'Times-Roman');
  RegisterClassAlias(TPdfTimesBold, 'Times-Bold');
  RegisterClassAlias(TPdfTimesItalic, 'Times-Italic');
  RegisterClassAlias(TPdfTimesBoldItalic, 'Times-BoldItalic');
//  RegisterClassAlias(TPdfScript, 'Script');
//  RegisterClassAlias(TPdfSymbol, 'Symbol');

  RegisterClassAlias(TPdfBitmapImage, 'Pdf-Bitmap');

  RegisterClassAlias(TPdfJpegImage, 'Pdf-Jpeg');
  
  I can install the package and I can put the components on the form but, at run time I get the following error:
  "Project GestioneMagazzino.exe raised exception class EClassNotFound with message 'Class Arial not found'."

**Comment by romankassebaum** [comment]
Okay, I reverted the last commit.
In your application, you have to use the unit Pdf.Fonts, so that the line

`  RegisterClassAlias(TPdfArial, 'Arial');`

Is called.

**Comment by MichaelAdam-AKA-Mike** [comment]
In Delphi 12.1 I can drop a PRPage control on the form but on Delphi 11.3 I still get the error, that class Arial cannot be found.
In both versions I installed PowerPDF with Get-it-Package-Manager.

**Comment by romankassebaum** [comment]
Maybe the Delphi 11.3 version has not been updated. I will check.

**Comment by romankassebaum** [comment]
Should be fixed now.

**Comment by MichaelAdam-AKA-Mike** [comment]
Thanks for the update. Now it also works in Delphi 11.3.
