### ISSUE TITLE
Range check error in TPdfType1Font.GetCharWidth with Chars > 255

### ISSUE THREAD

**Issue by BuwSh** [TurboPack/PowerPDF#2]
Hi,

if I use the €-sign (and certainly all other non-Ascii chars > 255) in my PDF form, with range settings enabled the library will crash.
This is because the FArray is only 256 big, but Ord of the €-sign is 8364.
I know it is not a perfect solution, but changing the function to this helps me as a workaround and prevents a crash.

```
{ TPdfType1Font }
function TPdfType1Font.GetCharWidth(AText: string; APos: integer): integer;
begin
  if ord(AText[APos]) >= Length(FArray) then
    result := 1000
  else
    result := FArray[ord(AText[APos])];
end;

```

Best regards
Simon

**Comment by romankassebaum** [comment]
I tried to use a dictionary. Could you please test it?

**Comment by BuwSh** [comment]
Hey Roman,

sorry I was on vacation last week, so I couldn't have a look at your code then.

I tried it with the problematic file and didn't get any error, so it looks good to me.
Thanks for the proper fix! :-)

Best regards
Simon

**Comment by BuwSh** [comment]
After a little bit more testing, I found out the fix did not calculate the char width at all.
It is easy noticeable on larger Texts. 

This is because the position is put as the key of the dictionary instead of the Ord() of the char of AText.

I fixed it like this, and now the size looks good and creates line-breaks on larger texts.

```
function TPdfType1Font.GetCharWidth(AText: string; APos: integer): integer;
var
  lDefaultWidth: Word;
begin
  if not FArray.TryGetValue(Ord(AText[APos]), Result) then // <--- before: if not FArray.TryGetValue(APos, Result) then
  begin
    // initialize char widths array by default value (if missing width parameter
    // is defined, use it as default value.)
    if Data.PdfNumberByName('MissingWidth') <> nil then
      lDefaultWidth := Data.PdfNumberByName('MissingWidth').Value
    else
      lDefaultWidth := 0;
    Result := lDefaultWidth;
  end;
end;
```

**Comment by romankassebaum** [comment]
You are right, I patched your fix.

**Comment by BuwSh** [comment]
Hey Roman,

you missed a ")" for the Ord function.

I also noticed that in both package installations, debug information is set to 0 instead of false. That leads to a compiler error in XE3.
Maybe you can correct this, if this does not collide with Delphi higher than XE3.

Best regards
Simon

**Comment by romankassebaum** [comment]
I'm sorry for the ')'.

The Berlin IDE automatically uses 0. No idea what I could do.
