### ISSUE TITLE
Russsian character

### ISSUE THREAD

**Issue by aazavid** [TurboPack/PowerPDF#4]
incorrect russion caracter, for Delphi use next code: 

```
 function Rus(mes: string):string;
  var  i: integer; 
  begin
    SetLength(Result,length(mes));
    for i:=1 to length(mes) do
      case mes[i] of
        'А'..'п' :Result[i] := Chr(Ord(mes[i]) - 64);
        'р'..'я' :Result[i] := Chr (Ord(mes [i] ) -16);
        else Result[i]:=mes[i];
      end;
  end; 
```

That use for c++ builder?

**Comment by romankassebaum** [comment]
I do not understand what you mean.

**Comment by aazavid** [comment]
In the generated PDF report instead of Russian letters displayed abracadabra - characters. It occurs when you add Russian letters in the caption Label

**Comment by romankassebaum** [comment]
I see.

But normally PowerPDF should be full Unicode.

Could you provide a small test project including the issue.

**Comment by aazavid** [comment]
Here is an example, hang on the click event. 

```
void __fastcall TForm1::Button1Click(TObject *Sender)
{
PReport1->BeginDoc();
PRLabel1->Caption = "Всем привет";
PReport1->Print(PRPage1);

PReport1->EndDoc();
}
```

The output goes abracadabra, with one character, like all the letters superimposed on each other.

**Comment by romankassebaum** [comment]
It seems that PowerPDF is simply Ansified:

// _WriteString
procedure _WriteString(const Value: string; AStream: TStream);
var
  sAnsi: AnsiString;
begin
  //The stream should be ansified
  sAnsi := AnsiString(Value);
  AStream.Write(PAnsiChar(sAnsi)^, Length(sAnsi));
//  AStream.Write(PChar(Value)^, Length(Value) \* SizeOf(Char));
end;

This is because PowerPDF uses WinAnsiEncoding inside the PDF:

  TYPE1_FONT_STR_TABLE: array[0..2] of TPDF_STR_TBL =(
                         (KEY: 'Type'; VAL: 'Font'),
                         (KEY: 'Subtype'; VAL: 'Type1'),
                         (KEY: 'Encoding'; VAL: 'WinAnsiEncoding')
                         );

Here is an article about this: http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf
And another interesting link: http://stackoverflow.com/questions/128162/unicode-in-pdf

At this point I don't know enough about the pdf specification to fix this.

**Comment by aazavid** [comment]
Where you have defined a font description?

It is necessary to write a table of differences. I could write it.

There is a table http://partners.adobe.com/public/developer/en/font/5013.Cyrillic_Font_Spec.pdf
and cp-1251 table on them and the differences in the definition of the font being built.

Example: 

```
/Type /Encoding

/BaseEncoding /WinAnsiEncoding

/Differences [217 /afii10043]
```

How descriptions charset depends on the font type.
For Type 1, TrueType and Type 3 fonts, you can specify either one of the standard encodings (MacRomanEncoding, MacExpertEncoding, WinAnsiEncoding) or specify the encoding, which is described in the Encoding Dictionary.
Codes in this dictionary describes three entries: Type (optional, must be the value of "Encoding" BaseEncoding, Differences.
Recorded Differences describes differences from the encoding specified in BaseEncoding (can take the same values ​​as the Encoding entry in the description of the font, or may be omitted). Differences The format is slightly different for different types of fonts. There still are some subtleties to cmap'ami that may be described in TrueType fonts.

**Comment by romankassebaum** [comment]
I see. It would be great if you could do this.

Just to say this I haven't written the PowerPDF lib. I only moved it to newer Delphi versions.

From what I understand about the code you should have a look at the unit PDFFonts.

**Comment by patuh9090** [comment]
[https://github.com/TurboPack/PowerPDF/pull/5/commits/1165d567c6e533739bddd0090ffefac6c460418e](url)

**Comment by aazavid** [comment]
````cpp
//...
char c[40];
pdf::Document doc(pdf::create_file(c));
doc.page_start(width, height);
pdf::Font times = doc.font_load("file=times.ttf; size=10; enc=windows-1251");
doc.page().canvas().text_font(times);
//...
doc.page().canvas().text(a,b,"Кириллица");
//...
doc.page_end();
doc.finalize();
````

just to load the font manually
