### ISSUE TITLE
No visual component after get it in 10.3.1

### ISSUE THREAD

**Issue by mochu33** [TurboPack/PowerPDF#6]
After installing PowerPDF with GetIt under C++ Builder 10.3.1, no components are intalled.

I see that all the bpl files are in the C:\Users\Public\Documents\Embarcadero\Studio\20.0\BPL, the bpi files in C:\Users\Public\Documents\Embarcadero\Studio\20.0\DCP and the source files and header files in %USERPROFILE%\Documents\Embarcadero\Studio\20.0\CatalogRepository\PowerPDF-1.3cb directory.

Do I need to copy this file to the Embarcadero package directory? or do I need to set my Environment Variables under my Tools->Options menú to acces the components? or do I need to install the components with the Component->Install component... menu? or ...

**Comment by mochu33** [comment]
No components to add

**Comment by alperyazgan** [comment]
How is it solved ?
I am expecting some components in a palette, right ?

```
procedure Register;
begin
  RegisterComponents('PowerPdf', [TPReport,
                                  TPRPage,
                                  TPRLayoutPanel,
                                  TPRGridPanel,
                                  TPRLabel,
                                  TPRText,
                                  TPRRect,
                                  TPREllipse,
                                  TPRImage,
                                  TPRJpegImage,
                                  TPRAnnotation
                                 ]);
end;
```
