### ISSUE TITLE
No Installed Visual Components found in C++ Builder Rio 10.3.2 CE

### ISSUE THREAD

**Issue by alperyazgan** [TurboPack/PowerPDF#7]
After installation thru getit manager and also by manual compilation and installation there exists no visual components and even no palette named _PowerPdf_ from design package _PowerPDFCD260.bpl_, what am I missing ? Any idea will be appreciated.

**Comment by alperyazgan** [comment]
Issue #6 is related but it is already closed with no explanation :-(

**Comment by alperyazgan** [comment]
I am expecting some components in a palette, right ?

```
procedure Register;
begin
  RegisterComponents('PowerPdf', [TPReport,
                                  TPRPage,
                                  TPRLayoutPanel,
                                  TPRGridPanel,
                                  TPRLabel,
                                  TPRText,
                                  TPRRect,
                                  TPREllipse,
                                  TPRImage,
                                  TPRJpegImage,
                                  TPRAnnotation
                                 ]);
end;
```

**Comment by JarekParal** [comment]
I have the same problem after installing the PowerPDF from `GetIt Packet Manager` to the C++ Builder 10.3 Rio. 

But the components are available in RAD Studio 10.3 Delphi. Are the PowerPDF components available only for Delphi VCL programming?

**Comment by JarekParal** [comment]
@romankassebaum Do you have some suggestion?

**Comment by alperyazgan** [comment]
Sorry, I haven’t test it on Delphi, but there should be no difference in both environments regarding component installation yet the whose package is written in pascal/Delphi like many others I have installed into C++ Builder?

**Comment by alperyazgan** [comment]
I am very disappointed when this issue is closed without any comment or explanation !?
