### ISSUE TITLE
No Installed Visual Components found in C++ Builder Rio 10.3.2 CE

### ISSUE THREAD

**Issue by alperyazgan** [TurboPack/PowerPDF#9]
Please refer to #7

**Comment by romankassebaum** [comment]
I could fix this in the 10.4.2 C++Builder IDE. In 10.3 I tried to fix it manually. The issue was that the unit PowerPDF.pas was also included in the runtime package. If the issue is still there, then you should remove it inside your Rio IDE and send me the changed package.

**Comment by alperyazgan** [comment]
Thanks for the reply, solved the problem now.
